Pizzeria/urls.py
#Users request pages by entering URLs into a browser and clicking links, so
#we’ll need to decide what URLs are needed. The home page URL is first:
#it’s the base URL people use to access the project.
from django.contrib import admin
from django.urls import path, include

#edit the default urls.py file in the pizzas folder
# the urlpatterns variable includes sets of URLs from 
# the apps in the project.
urlpatterns = [
    path('admin/', admin.site.urls), #includes the module admin.site.urls, which defines all the URLs that can be
                                    #requested from the admin site.
    path('', include('Pizzas.urls')),
    path('users/', include('users.urls')),   
]

pizzas/urls.py
#the path function, which is needed when mapping URLs to views
from django.urls import path

# the dot tells Python to import the views.py module from
# the same directory as the current urls.py module. 
from . import views

#The variable app+name helps Django distinguish this urls.py file from
# files of the same name in other apps within the project
app_name = 'Pizzas'

#The variable urlpatterns in this module is a list of individual pages
# that can be requested from the pizzas app


urlpatterns = [
    #the first argument is an empty string which matches the
    # base URL.
    # the second argument specifies the function name to call in views.py.
    # the third argument provides the name 'index' for this URL pattern to
    # refer to it later
    path('', views.index, name='index'),
    path('pizzas', views.pizzas, name = 'pizzas'),
    path('pizzas/<int:pizza_id>/', views.pizza, name = 'pizza'),
    path('new_topping/<int:pizza_id>/',views.new_topping, name='new_topping'),
    path('edit_topping/<int:topping_id>', views.edit_topping, name='edit_topping'),
    path('new_comment/<int:p_id>', views.new_comment, name='new_comment'),
]

users/urls.py
from django.urls import path, include
from . import views

app_name = 'users'

'''
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
'''

urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('register/', views.register, name= 'register'),
]

pizzas/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Pizza(models.Model):
    '''Type of pizzas.'''
    name = models.CharField(max_length = 200)
    date_added = models.DateTimeField(auto_now_add = True)

    def __str__(self):
        """returns back whatever it is in string method, string representation of model"""
        return self.name

class Topping(models.Model):
    '''Specific types of pizzas and its toppings'''
    pizza = models.ForeignKey(Pizza, on_delete = models.CASCADE)
    name = models.TextField()
    date_added = models.DateTimeField(auto_now_add = True)
    

    class Meta:
        verbose_name_plural = "toppings"

    def __str__(self):
        """Return a string representation of the topping"""
        return f"{self.name[:50]}..."

class Comment(models.Model):
    pizza = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    name = models.CharField(max_length = 200)
    
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name
    

users/models.py
from django.db import models

# Create your models here.

pizzas/forms.py
from django import forms

from .models import Topping, Comment, Pizza

class ToppingForm(forms.ModelForm):
    class Meta:
        Model = Topping #model you're going to use
        fields = ['name']
        labels = {'name':''}
        widgets = {'name': forms.Textarea(attrs={'cols': 80})}

class CommentForm(forms.ModelForm):
    class Meta:
        Model = Comment
        fields = ['name']
        labels = {'name':''}

pizzas/views.py
from django.shortcuts import render, redirect
from .models import Pizza, Topping, Comment
from .forms import ToppingForm, CommentForm
from django.contrib.auth.decorators import login_required
from django.http import Http404
# Create your views here.

# When a URL request matches the pattern we just defined, 
# Django looks for a function called index() in the views.py file.
# views - bringing in from models and show it on template html file
# but before that you need to add it to url.file creating a url.
def index(request):
    """The home page for Pizzeria."""
    return render(request, 'Pizzas/index.html')
@login_required
def pizzas(request):
    pizzas = Pizza.objects.order_by('date_added')
    #allows you to use template tag, variables in template file 
    context = {'pizzas' : pizzas}
    #load up the page to view
    return render(request, 'Pizzas/pizzas.html', context)
@login_required
def pizza(request, pizza_id):
    pizza = Pizza.objects.get(id = pizza_id)
    toppings = pizza.topping_set.order_by('date_added')

    context = {'pizza': pizza, 'toppings':toppings}

    return render(request, 'Pizzas/pizza.html', context)
@login_required
def new_topping(request, pizza_id):
    pizza = Pizza.objects.get(id = pizza_id)
    if request.method != 'POST':
        form = ToppingForm() 
    
    else:
        form = ToppingForm(data = request.POST)

        if form.is_valid():
            new_topping = form.save(commit = False)
            new_topping.pizza = pizza
            new_topping.owner = request.user
            new_topping.save()
            
            return redirect('Pizzas:pizza', pizza_id = pizza_id)

    context = {'form': form, 'pizza': pizza}
    return render(request, 'Pizzas/new_topping.html', context)

@login_required
def edit_topping(request, topping_id):
    topping = Topping.objects.get(id=topping_id)
    pizza = topping.pizza

    if pizza.owner != request.user:
        raise Http404
    if request.method != 'POST':
        form = ToppingForm(instance=topping)
    else:
        form = ToppingForm(instance=topping, data=request.POST)

    if form.is_valid():
        form.save()
        return redirect('Pizzas:pizza',pizza_id=pizza.id)

    context = {'topping':topping, 'pizza':pizza, 'form':form}  
    return render(request, 'Pizzas/edit_.html', context)

@login_required
def new_comment(request, p_id):
    pizza = Pizza.objects.get(id=p_id)

    if request.method != 'POST':
        form = CommentForm()
    
    else:
        form = CommentForm(data=request.POST)

        if form.is_valid():
            new_comment = form.save(commit=False)
            new_comment.pizza = pizza
            new_comment.owner = request.user
            new_comment.save()
            return redirect('Pizzas:pizza',pizza_id=p_id)

    context = {'form':form, 'pizza':pizza}
    return render(request, 'Pizzas/new_comment.html', context)

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm

def register(request):
    if request.method != 'POST':
        form = UserCreationForm()
    else:
        form = UserCreationForm(data=request.POST)
        
        if form.is_valid():
            new_user = form.save()
            login(request, new_user)
            return redirect('Pizzas:index')

    context = {'form':form}
    return render(request, 'registration/register.html', context)

pizzas/templates/pizzas/base.html
{% load bootstrap4 %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1,
    shrink-to-fit=no">
    <title>Pizzeria</title>

    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}

</head>
<body>

    <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
        
        <a class="navbar-brand" href="{% url 'Pizzas:index'%}">
            Pizzeria</a>

        <button class="navbar-toggler" type="button" data-toggle="collapse"
            data-target="#navbarCollapse" aria-controls="navbarCollapse"
            aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav item">
                    <a class="nav-link" href="{% url 'Pizzas:pizzas'%}">
                        Pizzas</a></li>
            </ul>
            <ul class="navbar-nav ml auto">
                {% if user.is_authenticated %}
                   <li class="nav-item">
                       <span class="navbar-text"}">Hello, {{user.username}}.</span>
                   </li>
                   <li class="nav-item">
                       <a class="nav-link" href="{% url 'users:logout' %}">Log out</a>
                   </li>
                {% else%}
                   <li class="nav-item">
                       <a class="nav-link" href="{% url 'users:register' %}">Register</a>
                   </li>
                   <li class="nav-item">
                       <a class="nav-link" href="{% url 'users:login' %}">Log in</a></li>
                {% endif %}
            </ul>
        </div>
    
    </nav>

    <main role="main" class="container">
        <div class="pb-2 mb-2 border-bottom">
            {% block page_header %}{% endblock page_header %}
        </div>
        <div>
            {% block content %}{% endblock content %}
        </div>
    </main>

</body>

</html>

pizzas/templates/pizzas/edit_topping.html
{% extends "Pizzas/base.html" %}

    {% block content %}

        <p><a href="{% url 'Pizzas:pizza' pizza.id %}">{{ pizza }}</a></p>
            <p>Edit the Pizzas Toppings</p>

        <form action="{% url 'Pizzas:edit_topping' pizza.id %}" method='post'>
            
            {% csrf_token %}
            {{ form.as_p }}

            <button name="submit">Save</button>
        </form>

    {% endblock content %}

pizzas/templates/pizzas/index.html
{% extends "Pizzas/base.html" %}

{% block page_header %}
 <div class="jumbotron">
    <img src="https://www.gstatic.com/bfe/apps/website/img/h/87450465-pizza-1440.jpg" alt="Pizza", width="300", height="300">
    <h1 class="display-3">We serve you good.</h1>
    <p class="lead">Better ingredients, Better Pizza! Welcome to Pizzeria!</p>
    <a class="btn btn-lg btn-primary" href="{% url 'users:register' %}"
        role="button">Register &raquo;</a>
 </div>

 <p> 
 </p> 

{% endblock page_header %}

pizzas/templates/pizzas/new_comment.html
{% extends "Pizzas/base.html" %}

    {% block content %}

        <p><a href="{% url 'Pizzas:pizza' pizza.id %}">{{ pizza }}</a></p>
            <p>Add a comment:</p>

        <form action="{% url 'Pizzas:new_comment' pizza.id %}" method='post'>
            
            {% csrf_token %}
            {{ form.as_p }}

            <button name="submit">Add comment</button>
        </form>

    {% endblock content %}

pizzas/templates/pizzas/new_topping.html
{% extends "Pizzas/base.html" %}

    {% block content %}

    <p><a href="{% url 'Pizzas:pizza' pizza.id %}">{{ pizza }} </a></p>

        <p>Add a new toppings: </p>

        
    <form action ="{% url 'Pizzas:new_topping' pizza.id %}" method = 'post'>
        {% csrf_token %}
        {{ form.as_p }}

        <button name = "submit">Add Topping</button>
    </form>

    {% endblock content %}

pizzas/templates/pizzas/pizza.html
{% extends "Pizzas/base.html" %}

{% block content %}

    <p> Pizza: {{ pizza }} </p>

    <ul>

        {% for topping in toppings %}


        <li> 
            
            <p>{{ topping.name|linebreaks }} </p> 
            <p>
                <a href="{% url 'Pizzas:edit_topping' topping.id %}">Edit topping</a>
            </p>
        </li> 

        {% empty %}

        <li> No toppings are added yet. </li>

            {% endfor %}

    </ul>
    <p>
        <a href="{% url 'Pizzas:new_topping' pizza.id %}">Add a new topping</a>
    </p>
    <ul>
        
        {% for comment in comments %}
        <li>
             <p> {{ comment.name|linebreaks }}</p>
        </li>
        {% empty %}

            <li> No comments. Please comment!</li>

        {% endfor %}

        </li>

    </ul>
    
    <p>
        <a href="{% url 'Pizzas:new_comment' pizza.id %}">Add a new comment</a>
    </p>
    
{% endblock content %}

pizzas/templates/pizzas/pizzas.html
{% extends "Pizzas/base.html" %}

{% block content %}

    <p> Pizzas </p>

    <ul>

        {% for pizza in pizzas %}


        <li> <a href = "{% url 'Pizzas:pizza' pizza.id %}">{{ pizza }} </li>
        </li>
    
        {% empty %}
            <li> No pizzas have been added yet! </li>
        {% endfor %}
    </ul>

    
{% endblock content %}